#!/usr/bin/env Rscript
###############################################################################
## _create_ia_latex.R - Compile Internet Appendix LaTeX Document
## ---------------------------------------------------------------------------
##
## This script assembles all IA tables and figures into a compilable LaTeX
## document structure. Run this after _run_ia_results.R.
##
## OUTPUTS:
##   ia/output/paper/latex/
##     ia_tables.tex    - All tables combined
##     ia_figures.tex   - All figures combined
##     ia_main.tex      - Main document (includes tables and figures)
##
## USAGE:
##   Rscript ia/_create_ia_latex.R
##
###############################################################################

###############################################################################
## SECTION 1: SETUP
###############################################################################

# Ensure we're in project root
if (basename(getwd()) == "ia") {
  setwd("..")
}
main_path <- getwd()

# Paths
ia_output   <- file.path(main_path, "ia", "output", "paper")
tables_dir  <- file.path(ia_output, "tables")
figures_dir <- file.path(ia_output, "figures")
latex_dir   <- file.path(ia_output, "latex")

# Create latex directory
if (!dir.exists(latex_dir)) {
  dir.create(latex_dir, recursive = TRUE)
}

verbose <- TRUE

###############################################################################
## SECTION 2: TABLE ORDERING
###############################################################################

# Define table order (main tables first, then appendix)
main_table_order <- c(
  "table_ia_is_pricing.tex",
  "table_ia_os_pricing.tex"
)

# Pattern for probability tables (generated per model)
prob_table_pattern <- "^table_a1_posterior_probs_"

###############################################################################
## SECTION 3: SCAN FOR FILES
###############################################################################

cat("\n")
cat("========================================\n")
cat("CREATING IA LATEX DOCUMENT\n")
cat("========================================\n\n")

# Scan tables
if (dir.exists(tables_dir)) {
  all_tables <- list.files(tables_dir, pattern = "\\.tex$", full.names = FALSE)
  cat("Found", length(all_tables), "table files in:", tables_dir, "\n")
} else {
  all_tables <- character(0)
  warning("Tables directory does not exist: ", tables_dir)
}

# Scan figures
if (dir.exists(figures_dir)) {
  all_figures <- list.files(figures_dir, pattern = "\\.pdf$", full.names = FALSE)
  cat("Found", length(all_figures), "figure files in:", figures_dir, "\n")
} else {
  all_figures <- character(0)
  warning("Figures directory does not exist: ", figures_dir)
}

cat("\n")

###############################################################################
## SECTION 4: CREATE ia_tables.tex
###############################################################################

cat("Creating ia_tables.tex...\n")

# Separate main tables from probability tables
main_tables <- intersect(main_table_order, all_tables)
prob_tables <- all_tables[grepl(prob_table_pattern, all_tables)]
other_tables <- setdiff(all_tables, c(main_tables, prob_tables))

# Build tables.tex content
tables_tex <- character()
tables_tex <- c(tables_tex, "% ia_tables.tex - Auto-generated by _create_ia_latex.R")
tables_tex <- c(tables_tex, "% Internet Appendix Tables")
tables_tex <- c(tables_tex, "")

# Main pricing tables
if (length(main_tables) > 0) {
  tables_tex <- c(tables_tex, "% Pricing Tables")
  tables_tex <- c(tables_tex, "% ==============")
  for (tbl in main_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Probability tables (one per model)
if (length(prob_tables) > 0) {
  tables_tex <- c(tables_tex, "% Posterior Probability Tables")
  tables_tex <- c(tables_tex, "% ============================")
  for (tbl in sort(prob_tables)) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Other tables
if (length(other_tables) > 0) {
  tables_tex <- c(tables_tex, "% Additional Tables")
  tables_tex <- c(tables_tex, "% =================")
  for (tbl in other_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Write tables.tex
tables_tex_file <- file.path(latex_dir, "ia_tables.tex")
writeLines(tables_tex, tables_tex_file)
cat("  Written:", tables_tex_file, "\n")
cat("  Included", length(all_tables), "tables\n")

###############################################################################
## SECTION 5: CREATE ia_figures.tex
###############################################################################

cat("\nCreating ia_figures.tex...\n")

figures_tex <- character()
figures_tex <- c(figures_tex, "% ia_figures.tex - Auto-generated by _create_ia_latex.R")
figures_tex <- c(figures_tex, "% Internet Appendix Figures")
figures_tex <- c(figures_tex, "")

# Sort figures by name
sorted_figures <- sort(all_figures)

for (fig in sorted_figures) {
  fig_name <- tools::file_path_sans_ext(fig)

  figures_tex <- c(figures_tex, "\\begin{figure}[htbp]")
  figures_tex <- c(figures_tex, "\\centering")
  figures_tex <- c(figures_tex, paste0("\\includegraphics[width=\\textwidth]{../figures/", fig, "}"))
  figures_tex <- c(figures_tex, paste0("\\caption{", gsub("_", "\\\\_", fig_name), "}"))
  figures_tex <- c(figures_tex, paste0("\\label{fig:", fig_name, "}"))
  figures_tex <- c(figures_tex, "\\end{figure}")
  figures_tex <- c(figures_tex, "\\clearpage")
  figures_tex <- c(figures_tex, "")
}

figures_tex_file <- file.path(latex_dir, "ia_figures.tex")
writeLines(figures_tex, figures_tex_file)
cat("  Written:", figures_tex_file, "\n")
cat("  Included", length(all_figures), "figures\n")

###############################################################################
## SECTION 6: CREATE ia_main.tex
###############################################################################

cat("\nCreating ia_main.tex...\n")

main_tex <- c(
  "% ia_main.tex - Internet Appendix Main Document",
  "% Auto-generated by _create_ia_latex.R",
  "%",
  "% Compile with: pdflatex ia_main.tex",
  "",
  "\\documentclass[11pt]{article}",
  "",
  "% Packages",
  "\\usepackage[margin=1in]{geometry}",
  "\\usepackage{graphicx}",
  "\\usepackage{booktabs}",
  "\\usepackage{amsmath}",
  "\\usepackage{amssymb}",
  "\\usepackage{setspace}",
  "\\usepackage{hyperref}",
  "",
  "% Title",
  "\\title{Internet Appendix:\\\\The Co-Pricing Factor Zoo}",
  "\\author{Dickerson, Julliard, Mueller}",
  "\\date{\\today}",
  "",
  "\\begin{document}",
  "",
  "\\maketitle",
  "",
  "\\section{Additional Tables}",
  "\\input{ia_tables}",
  "",
  "\\section{Additional Figures}",
  "\\input{ia_figures}",
  "",
  "\\end{document}"
)

main_tex_file <- file.path(latex_dir, "ia_main.tex")
writeLines(main_tex, main_tex_file)
cat("  Written:", main_tex_file, "\n")

###############################################################################
## SECTION 7: SUMMARY
###############################################################################

cat("\n")
cat("========================================\n")
cat("IA LATEX DOCUMENT CREATED\n")
cat("========================================\n")
cat("\n")
cat("Files created in:", latex_dir, "\n")
cat("  - ia_main.tex     (main document)\n")
cat("  - ia_tables.tex   (all tables)\n")
cat("  - ia_figures.tex  (all figures)\n")
cat("\n")
cat("To compile:\n")
cat("  cd", latex_dir, "\n")
cat("  pdflatex ia_main.tex\n")
cat("\n")
