#!/usr/bin/env Rscript
###############################################################################
## _create_ia_latex.R - Compile Internet Appendix LaTeX Document
## ---------------------------------------------------------------------------
##
## This script assembles all IA tables and figures into a compilable LaTeX
## document structure. Run this after _run_ia_results.R.
##
## OUTPUTS:
##   ia/output/paper/latex/
##     ia_tables.tex    - All tables combined
##     ia_figures.tex   - All figures combined
##     ia_main.tex      - Main document (includes tables and figures)
##
## USAGE:
##   Rscript ia/_create_ia_latex.R
##
###############################################################################

###############################################################################
## SECTION 1: SETUP
###############################################################################

# Ensure we're in project root
if (basename(getwd()) == "ia") {
  setwd("..")
}
main_path <- getwd()

# Paths
ia_output   <- file.path(main_path, "ia", "output", "paper")
tables_dir  <- file.path(ia_output, "tables")
figures_dir <- file.path(ia_output, "figures")
latex_dir   <- file.path(ia_output, "latex")

# Create latex directory
if (!dir.exists(latex_dir)) {
  dir.create(latex_dir, recursive = TRUE)
}

verbose <- TRUE

###############################################################################
## SECTION 2: TABLE ORDERING
###############################################################################

# Define table order (main tables first, then appendix)
main_table_order <- c(
  "table_ia_is_pricing.tex",
  "table_ia_os_pricing.tex"
)

# Pattern for probability tables (generated per model)
prob_table_pattern <- "^table_a1_posterior_probs_"

# Treasury tables (appear after probability tables)
treasury_table_order <- c(
  "table_treasury_posterior_probs.tex",
  "table_treasury_sr_decomp.tex"
)

# Tables that should appear LAST (in order)
last_table_order <- c(
  "table_duration_pricing.tex"
)

###############################################################################
## SECTION 3: SCAN FOR FILES
###############################################################################

cat("\n")
cat("========================================\n")
cat("CREATING IA LATEX DOCUMENT\n")
cat("========================================\n\n")

# Scan tables
if (dir.exists(tables_dir)) {
  all_tables <- list.files(tables_dir, pattern = "\\.tex$", full.names = FALSE)
  cat("Found", length(all_tables), "table files in:", tables_dir, "\n")
} else {
  all_tables <- character(0)
  warning("Tables directory does not exist: ", tables_dir)
}

# Scan figures
if (dir.exists(figures_dir)) {
  all_figures <- list.files(figures_dir, pattern = "\\.pdf$", full.names = FALSE)
  cat("Found", length(all_figures), "figure files in:", figures_dir, "\n")
} else {
  all_figures <- character(0)
  warning("Figures directory does not exist: ", figures_dir)
}

cat("\n")

###############################################################################
## SECTION 4: CREATE ia_tables.tex
###############################################################################

cat("Creating ia_tables.tex...\n")

# Separate main tables from probability tables, treasury, and last tables
main_tables <- intersect(main_table_order, all_tables)
prob_tables <- all_tables[grepl(prob_table_pattern, all_tables)]
treasury_tables <- intersect(treasury_table_order, all_tables)
last_tables <- intersect(last_table_order, all_tables)
other_tables <- setdiff(all_tables, c(main_tables, prob_tables, treasury_tables, last_tables))

# Build tables.tex content
tables_tex <- character()
tables_tex <- c(tables_tex, "% ia_tables.tex - Auto-generated by _create_ia_latex.R")
tables_tex <- c(tables_tex, "% Internet Appendix Tables")
tables_tex <- c(tables_tex, "")

# Main pricing tables
if (length(main_tables) > 0) {
  tables_tex <- c(tables_tex, "% Pricing Tables")
  tables_tex <- c(tables_tex, "% ==============")
  for (tbl in main_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Probability tables (one per model)
if (length(prob_tables) > 0) {
  tables_tex <- c(tables_tex, "% Posterior Probability Tables")
  tables_tex <- c(tables_tex, "% ============================")
  for (tbl in sort(prob_tables)) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Treasury tables (treasury component analysis)
if (length(treasury_tables) > 0) {
  tables_tex <- c(tables_tex, "% Treasury Component Tables")
  tables_tex <- c(tables_tex, "% =========================")
  for (tbl in treasury_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Other tables
if (length(other_tables) > 0) {
  tables_tex <- c(tables_tex, "% Additional Tables")
  tables_tex <- c(tables_tex, "% =================")
  for (tbl in other_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Last tables (e.g., duration pricing - should appear at the very end)
if (length(last_tables) > 0) {
  tables_tex <- c(tables_tex, "% Final Tables (Duration Pricing)")
  tables_tex <- c(tables_tex, "% ================================")
  for (tbl in last_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Write tables.tex
tables_tex_file <- file.path(latex_dir, "ia_tables.tex")
writeLines(tables_tex, tables_tex_file)
cat("  Written:", tables_tex_file, "\n")
cat("  Included", length(all_tables), "tables\n")

###############################################################################
## SECTION 5: CREATE ia_figures.tex
###############################################################################

cat("\nCreating ia_figures.tex...\n")

figures_tex <- character()
figures_tex <- c(figures_tex, "% ia_figures.tex - Auto-generated by _create_ia_latex.R")
figures_tex <- c(figures_tex, "% Internet Appendix Figures")
figures_tex <- c(figures_tex, "")

# Sort figures by name
sorted_figures <- sort(all_figures)

for (fig in sorted_figures) {
  fig_name <- tools::file_path_sans_ext(fig)

  figures_tex <- c(figures_tex, "\\begin{figure}[htbp]")
  figures_tex <- c(figures_tex, "\\centering")
  figures_tex <- c(figures_tex, paste0("\\includegraphics[width=\\textwidth]{../figures/", fig, "}"))
  figures_tex <- c(figures_tex, paste0("\\caption{", gsub("_", "\\\\_", fig_name), "}"))
  figures_tex <- c(figures_tex, paste0("\\label{fig:", fig_name, "}"))
  figures_tex <- c(figures_tex, "\\end{figure}")
  figures_tex <- c(figures_tex, "\\clearpage")
  figures_tex <- c(figures_tex, "")
}

figures_tex_file <- file.path(latex_dir, "ia_figures.tex")
writeLines(figures_tex, figures_tex_file)
cat("  Written:", figures_tex_file, "\n")
cat("  Included", length(all_figures), "figures\n")

###############################################################################
## SECTION 6: CREATE ia_main.tex (based on base_document.txt)
###############################################################################

cat("\nCreating ia_main.tex...\n")

# Read the base document template
base_doc_path <- file.path(main_path, "base_document.txt")

if (!file.exists(base_doc_path)) {
  warning("base_document.txt not found. Creating simple ia_main.tex instead.")

  main_tex <- c(
    "% ia_main.tex - Internet Appendix Main Document",
    "% Auto-generated by _create_ia_latex.R",
    "%",
    "% Compile with: pdflatex ia_main.tex",
    "",
    "\\documentclass[11pt]{article}",
    "\\usepackage[margin=1in]{geometry}",
    "\\usepackage{graphicx}",
    "\\usepackage{booktabs}",
    "\\usepackage{amsmath}",
    "\\usepackage{amssymb}",
    "\\usepackage{setspace}",
    "\\usepackage{hyperref}",
    "",
    "\\title{Internet Appendix for:\\\\The Co-Pricing Factor Zoo}",
    "\\author{Dickerson, Julliard, Mueller}",
    "\\date{\\today}",
    "",
    "\\begin{document}",
    "\\maketitle",
    "",
    "\\input{ia_tables}",
    "\\input{ia_figures}",
    "",
    "\\end{document}"
  )

} else {
  # Read base document
  base_lines <- readLines(base_doc_path)

  # Modify for Internet Appendix
  main_tex <- base_lines

  # 1. Change title
  title_idx <- grep("\\\\title\\{", main_tex)
  if (length(title_idx) > 0) {
    main_tex[title_idx] <- "\\title{"
    main_tex[title_idx + 1] <- "\t{\\textbf{Internet Appendix for The Co-Pricing Factor Zoo}}}"
  }

  # 2. Change abstract
  abstract_start <- grep("\\\\begin\\{abstract\\}", main_tex)
  abstract_end <- grep("\\\\end\\{abstract\\}", main_tex)

  if (length(abstract_start) > 0 && length(abstract_end) > 0) {
    new_abstract <- c(
      "\\begin{abstract}",
      "\\singlespacing",
      "\\noindent",
      "{",
      "This Internet Appendix provides additional results for ``The Co-Pricing Factor Zoo.''",
      "We present robustness analyses examining models with and without an intercept (constant) term.",
      "Tables report posterior factor probabilities and market prices of risk for bond-only, stock-only, and joint bond-stock models.",
      "Figures display the posterior probability distributions across different prior Sharpe ratio shrinkage levels.",
      "} ",
      "\\end{abstract}"
    )

    # Replace abstract section
    main_tex <- c(
      main_tex[1:(abstract_start - 1)],
      new_abstract,
      main_tex[(abstract_end + 1):length(main_tex)]
    )
  }

  # 3. Remove keywords and JEL codes (find and remove those lines)
  keywords_idx <- grep("emph\\{Keywords\\}", main_tex)
  jel_idx <- grep("JEL Classification", main_tex)

  if (length(keywords_idx) > 0) {
    main_tex[keywords_idx] <- "% Keywords removed for Internet Appendix"
  }
  if (length(jel_idx) > 0) {
    main_tex[jel_idx] <- "% JEL codes removed for Internet Appendix"
  }

  # 4. Replace input files with IA versions
  # Find \input{tables.tex} and replace
  tables_input_idx <- grep("\\\\input\\{tables\\.tex\\}", main_tex)
  if (length(tables_input_idx) > 0) {
    main_tex[tables_input_idx] <- "\\input{ia_tables.tex}"
  }

  # Find \input{figures.tex} and replace
  figures_input_idx <- grep("\\\\input\\{figures\\.tex\\}", main_tex)
  if (length(figures_input_idx) > 0) {
    main_tex[figures_input_idx] <- "\\input{ia_figures.tex}"
  }

  # 5. Remove bibliography section (find and comment out)
  bib_start <- grep("%%%%.*References", main_tex)
  bib_style_idx <- grep("\\\\bibliographystyle", main_tex)
  bib_idx <- grep("\\\\bibliography\\{", main_tex)

  if (length(bib_style_idx) > 0) {
    main_tex[bib_style_idx] <- "% \\bibliographystyle{apalike}  % Removed for IA"
  }
  if (length(bib_idx) > 0) {
    main_tex[bib_idx] <- "% \\bibliography{bibliography}  % Removed for IA"
  }

  # 6. Remove or simplify appendix section at the end
  appendix_header_idx <- grep("%%%%%%%% Main Appendix", main_tex)
  app_tables_idx <- grep("\\\\input\\{app_tables\\.tex\\}", main_tex)

  if (length(app_tables_idx) > 0) {
    main_tex[app_tables_idx] <- "% \\input{app_tables.tex}  % Not needed for IA"
  }

  # Remove the "Appendix" center header since this IS the appendix
  appendix_center_idx <- grep("LARGE.*textbf\\{Appendix\\}", main_tex)
  if (length(appendix_center_idx) > 0) {
    # Comment out the appendix header block
    for (i in (appendix_center_idx - 2):(appendix_center_idx + 1)) {
      if (i > 0 && i <= length(main_tex)) {
        main_tex[i] <- paste0("% ", main_tex[i])
      }
    }
  }
}

main_tex_file <- file.path(latex_dir, "ia_main.tex")
writeLines(main_tex, main_tex_file)
cat("  Written:", main_tex_file, "\n")
cat("  Based on: base_document.txt\n")

###############################################################################
## SECTION 7: SUMMARY
###############################################################################

cat("\n")
cat("========================================\n")
cat("IA LATEX DOCUMENT CREATED\n")
cat("========================================\n")
cat("\n")
cat("Files created in:", latex_dir, "\n")
cat("  - ia_main.tex     (main document)\n")
cat("  - ia_tables.tex   (all tables)\n")
cat("  - ia_figures.tex  (all figures)\n")
cat("\n")
cat("To compile:\n")
cat("  cd", latex_dir, "\n")
cat("  pdflatex ia_main.tex\n")
cat("\n")
