#!/usr/bin/env Rscript
###############################################################################
## _create_ia_latex.R - Assemble Internet Appendix LaTeX Document
## ---------------------------------------------------------------------------
##
## Paper role: Assemble the IA LaTeX tree from generated IA tables and figures.
## Paper refs: IA.6, IA.7, IA.9, IA.10; docs/paper/co-pricing-factor-zoo.ai-optimized.md
## Outputs:
##   ia/output/paper/latex/
##     ia_tables.tex
##     ia_figures.tex
##     ia_main.tex
##
## PDF compilation is a separate public step via tools/build_ia_paper.*.
###############################################################################

parse_args <- function(args = commandArgs(trailingOnly = TRUE)) {
  opts <- list(show_help = FALSE)

  for (arg in args) {
    if (identical(arg, "--help") || identical(arg, "-h")) {
      opts$show_help <- TRUE
    } else {
      stop("Unknown argument: ", arg, call. = FALSE)
    }
  }

  opts
}

opts <- parse_args()
if (isTRUE(opts$show_help)) {
  cat(
    "Usage: Rscript ia/_create_ia_latex.R [options]\n\n",
    "Options:\n",
    "  --help, -h   Show this help message\n\n",
    "This script assembles ia/output/paper/latex/ia_main.tex. Use tools/build_ia_paper.* to compile the PDF.\n",
    sep = ""
  )
  quit(save = "no", status = 0)
}

if (basename(getwd()) == "ia") {
  setwd("..")
}
main_path <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
source(file.path("code_base", "ia_run_helpers.R"))

ia_output <- file.path(main_path, "ia", "output", "paper")
tables_dir <- file.path(ia_output, "tables")
figures_dir <- file.path(ia_output, "figures")
latex_dir <- file.path(ia_output, "latex")
dir.create(latex_dir, recursive = TRUE, showWarnings = FALSE)

resolve_manifest_matches <- function(repo_root = getwd()) {
  manifest <- implemented_ia_manifest_outputs(repo_root)
  resolved <- vector("list", nrow(manifest))

  for (idx in seq_len(nrow(manifest))) {
    pattern <- file.path(repo_root, manifest$output_path[[idx]])
    matches <- Sys.glob(pattern)
    resolved[[idx]] <- data.frame(
      exhibit_id = manifest$exhibit_id[[idx]],
      output_path = manifest$output_path[[idx]],
      file = matches,
      stringsAsFactors = FALSE
    )
  }

  resolved <- Filter(function(x) nrow(x) > 0, resolved)
  if (length(resolved) == 0) {
    return(data.frame(exhibit_id = character(), output_path = character(), file = character(), stringsAsFactors = FALSE))
  }

  do.call(rbind, resolved)
}

ia_output_validation <- validate_ia_manifest_outputs(main_path)
if (!isTRUE(ia_output_validation$ok)) {
  stop(
    "IA LaTeX assembly cannot proceed because required IA outputs are missing.\n",
    format_ia_output_issues(ia_output_validation),
    call. = FALSE
  )
}

resolved_outputs <- resolve_manifest_matches(main_path)
table_rows <- resolved_outputs[grepl("/tables/", resolved_outputs$output_path, fixed = TRUE), , drop = FALSE]
figure_rows <- resolved_outputs[grepl("/figures/", resolved_outputs$output_path, fixed = TRUE), , drop = FALSE]

cat("\n========================================\n")
cat("ASSEMBLING IA LATEX TREE\n")
cat("========================================\n")
cat("Tables matched:  ", nrow(table_rows), "\n", sep = "")
cat("Figures matched: ", nrow(figure_rows), "\n\n", sep = "")

tables_tex <- c(
  "% ia_tables.tex - Auto-generated by ia/_create_ia_latex.R",
  "% Internet Appendix tables",
  ""
)

if (nrow(table_rows) > 0) {
  for (idx in seq_len(nrow(table_rows))) {
    rel_path <- normalizePath(table_rows$file[[idx]], winslash = "/", mustWork = TRUE)
    rel_path <- sub(paste0("^", gsub("([\\^\\$\\.\\|\\(\\)\\[\\]\\*\\+\\?\\\\])", "\\\\\\1", normalizePath(latex_dir, winslash = "/", mustWork = TRUE)), "/?"), "", rel_path)
    rel_path <- file.path("..", "tables", basename(table_rows$file[[idx]]))
    tables_tex <- c(tables_tex, paste0("\\input{", rel_path, "}"), "\\clearpage", "")
  }
}

writeLines(tables_tex, file.path(latex_dir, "ia_tables.tex"))
cat("Written: ", file.path(latex_dir, "ia_tables.tex"), "\n", sep = "")

figure_caption <- function(exhibit_id, file_name, duplicates) {
  # Keep captions human-readable and avoid leaking raw underscore-heavy basenames
  # into LaTeX text when a manifest pattern matches multiple files.
  exhibit_id
}

ia_figure_metadata <- function(exhibit_id) {
  switch(
    exhibit_id,
    "ISOS Switch Posterior Probability Figure" = list(
      title = "Posterior probabilities: IS/OS switch.",
      note_lines = c(
        "Posterior probabilities, $\\mathbb{E}[\\gamma_j|\\text{data}]$, of the 54 bond and stock factors in the co-pricing factor zoo.",
        "The prior for each factor inclusion is a Beta(1, 1), yielding a prior expectation for $\\gamma_j$ of 50\\%. Results are shown for different values of the prior Sharpe ratio, $\\sqrt{\\mathbb{E}_\\pi [SR^2_{\\bm{f}} \\mid \\sigma^2]}$, with values set to 20\\%, 40\\%, 60\\% and 80\\% of the ex post maximum Sharpe ratio of the test assets.",
        "Labels are ordered by the average posterior probability across the four levels of shrinkage. Test assets are the 154 out-of-sample bond and stock portfolios and 40 tradable bond and stock factors used in this replication. The sample period is 1986:01 to 2022:12 ($T = 444$)."
      )
    ),
    "Sparse Posterior Probability Figure" = list(
      title = "Posterior probabilities: imposing sparsity.",
      note_lines = c(
        "Posterior probabilities, $\\mathbb{E}[\\gamma_j|\\text{data}]$, of the 54 bond and stock factors in the co-pricing factor zoo.",
        "We encode sparsity by choosing the prior mean and variance of $\\omega_j$, $\\mathbb{E}[\\omega_j] = \\frac{a_{\\omega}}{a_{\\omega}+b_{\\omega}}$ and $\\operatorname{Var}(\\omega_j) = \\frac{a_{\\omega}b_{\\omega}}{(a_{\\omega}+b_{\\omega})^{2}(a_{\\omega}+b_{\\omega}+1)}$.",
        "We set $a_{\\omega} \\approx 3.54$ and $b_{\\omega} \\approx 34.66$ so that the prior expectation of the number of active factors is close to five out of $K = 54$, and the prior two-standard-deviation credible interval spans roughly zero to ten factors.",
        "The implied prior for each factor inclusion is Beta$(3.54, 34.66)$, yielding a prior expectation for $\\gamma_j$ of about 9.25\\%. Results are shown for different values of the prior Sharpe ratio, $\\sqrt{\\mathbb{E}_\\pi [SR^2_{\\bm{f}} \\mid \\sigma^2]}$, with values set to 20\\%, 40\\%, 60\\% and 80\\% of the ex post maximum Sharpe ratio of the test assets.",
        "Labels are ordered by the average posterior probability across the four levels of shrinkage. Test assets are the 83 bond and stock portfolios and 40 tradable bond and stock factors used in this replication. The sample period is 1986:01 to 2022:12 ($T = 444$)."
      )
    ),
    "Treasury NFac SR Figure" = list(
      title = "Posterior SDF dimensionality and Sharpe ratios: Treasury component.",
      note_lines = c(
        "Posterior distributions of the number of factors to be included in the bond SDF (top panel) and of the SDF-implied Sharpe ratio (bottom panel), computed using the 14 non-tradable and 16 tradable bond factors in the treasury-component specification.",
        "The prior distribution for the $j^{\\text{th}}$ factor inclusion is a Beta(1, 1), yielding a flat prior for the SDF dimensionality depicted in the top panel. The prior Sharpe ratio is set to 80\\% of the ex post maximum Sharpe ratio of the Treasury component of the 50 corporate bond portfolios and 16 bond tradable factors used in this replication.",
        "The sample period is 1986:01 to 2022:12 ($T = 444$)."
      )
    ),
    "Treasury Posterior Bars Figure" = list(
      title = "Posterior factor probabilities and risk prices: Treasury component.",
      note_lines = c(
        "The figure reports posterior probabilities, $\\mathbb{E}[\\gamma_j|\\text{data}]$, and posterior means of annualized market prices of risk, $\\mathbb{E}[\\lambda_j|\\text{data}]$, of the 14 non-tradable and 16 tradable bond factors in the treasury-component specification.",
        "The prior for each factor inclusion is a Beta(1, 1), yielding a prior expectation for $\\gamma_j$ of 50\\%. The prior Sharpe ratio is set to 80\\% of the ex post maximum Sharpe ratio of the Treasury component of the 50 corporate bond portfolios used in this replication.",
        "The sample period is 1986:01 to 2022:12 ($T = 444$)."
      )
    ),
    "Treasury Posterior Probability Figure" = list(
      title = "Posterior probabilities: Treasury component.",
      note_lines = c(
        "Posterior probabilities, $\\mathbb{E}[\\gamma_j|\\text{data}]$, of the 14 non-tradable and 16 tradable bond factors in the treasury-component specification.",
        "The prior for each factor inclusion is a Beta(1, 1), yielding a prior expectation for $\\gamma_j$ of 50\\%. Results are shown for different values of the prior Sharpe ratio, $\\sqrt{\\mathbb{E}_\\pi [SR^2_{\\bm{f}} \\mid \\sigma^2]}$, with values set to 20\\%, 40\\%, 60\\% and 80\\% of the ex post maximum Sharpe ratio of the test assets.",
        "Labels are ordered by the average posterior probability across the four levels of shrinkage. Test assets are the Treasury component of the 50 corporate bond portfolios and the 16 tradable bond factors used in this replication. The sample period is 1986:01 to 2022:12 ($T = 444$)."
      )
    ),
    "Treasury Weighted DR-Tilt Figure" = list(
      title = "Posterior factor probabilities and risk prices: Treasury component with DR tilt.",
      note_lines = c(
        "The figure reports posterior probabilities, $\\mathbb{E}[\\gamma_j|\\text{data}]$, and posterior means of annualized market prices of risk, $\\mathbb{E}[\\lambda_j|\\text{data}]$, of the 14 non-tradable and 16 tradable bond factors in the treasury-component specification.",
        "We tilt the prior for each factor inclusion through the $\\kappa$ vector using weights informed by the cash-flow and discount-rate news decomposition in the Internet Appendix analysis, so discount-rate-classified factors receive positive weights and cash-flow-classified factors receive negative weights.",
        "The prior Sharpe ratio is set to 80\\% of the ex post maximum Sharpe ratio of the Treasury component of the 50 corporate bond portfolios used in this replication. The sample period is 1986:01 to 2022:12 ($T = 444$)."
      )
    ),
    list(
      title = exhibit_id,
      note_lines = NULL
    )
  )
}

figure_groups <- split(figure_rows, figure_rows$exhibit_id)
figures_tex <- c(
  "% ia_figures.tex - Auto-generated by ia/_create_ia_latex.R",
  "% Internet Appendix figures",
  ""
)

for (group_name in names(figure_groups)) {
  group_rows <- figure_groups[[group_name]]
  duplicates <- nrow(group_rows)
  for (idx in seq_len(duplicates)) {
    file_name <- basename(group_rows$file[[idx]])
    figure_meta <- ia_figure_metadata(group_name)
    caption <- ia_value_or(figure_meta$title, figure_caption(group_name, file_name, duplicates))
    label <- paste0(
      "fig:",
      gsub("[^a-z0-9]+", "-", tolower(tools::file_path_sans_ext(file_name)))
    )
    figures_tex <- c(
      figures_tex,
      "\\begin{figure}[htbp]",
      "\\centering",
      paste0("\\includegraphics[width=\\textwidth]{../figures/", file_name, "}"),
      paste0("\\caption{", caption, "}"),
      paste0("\\label{", label, "}"),
      if (is.null(figure_meta$note_lines)) NULL else c(
        "\\begin{justify}",
        "\\vspace{-2mm}",
        "\\begin{spacing}{1}",
        "{\\footnotesize",
        figure_meta$note_lines,
        "}",
        "\\end{spacing}",
        "\\end{justify}"
      ),
      "\\end{figure}",
      "\\clearpage",
      ""
    )
  }
}

writeLines(figures_tex, file.path(latex_dir, "ia_figures.tex"))
cat("Written: ", file.path(latex_dir, "ia_figures.tex"), "\n", sep = "")

main_tex <- c(
  "% ia_main.tex - Internet Appendix Main Document",
  "% Auto-generated by ia/_create_ia_latex.R",
  "\\documentclass[11pt]{article}",
  "\\usepackage[margin=1in]{geometry}",
  "\\usepackage{graphicx}",
  "\\usepackage{booktabs}",
  "\\usepackage{amsmath,amssymb}",
  "\\usepackage{bm}",
  "\\usepackage{setspace}",
  "\\usepackage{caption}",
  "\\usepackage{subcaption}",
  "\\usepackage{float}",
  "\\usepackage{placeins}",
  "\\usepackage{multirow}",
  "\\usepackage{makecell}",
  "\\usepackage{array}",
  "\\usepackage[table]{xcolor}",
  "\\usepackage{ragged2e}",
  "\\usepackage[hidelinks]{hyperref}",
  "",
  "\\title{Internet Appendix for The Co-Pricing Factor Zoo}",
  "\\author{Replication Package}",
  "\\date{\\today}",
  "",
  "\\begin{document}",
  "\\maketitle",
  "\\begin{abstract}",
  "\\noindent This Internet Appendix document assembles the implemented robustness outputs generated by the replication package. The generated tables and figures below reflect the executable IA subset currently supported in the repository.",
  "\\end{abstract}",
  "\\tableofcontents",
  "\\clearpage",
  "\\section*{Tables}",
  "\\addcontentsline{toc}{section}{Tables}",
  "\\clearpage",
  "\\FloatBarrier",
  "\\input{ia_tables.tex}",
  "\\FloatBarrier",
  "\\clearpage",
  "\\section*{Figures}",
  "\\addcontentsline{toc}{section}{Figures}",
  "\\FloatBarrier",
  "\\input{ia_figures.tex}",
  "\\FloatBarrier",
  "\\end{document}"
)

writeLines(main_tex, file.path(latex_dir, "ia_main.tex"))
cat("Written: ", file.path(latex_dir, "ia_main.tex"), "\n", sep = "")

cat("\n========================================\n")
cat("IA LATEX TREE READY\n")
cat("========================================\n")
cat("Next step:\n")
cat("  powershell -ExecutionPolicy Bypass -File tools\\build_ia_paper.ps1\n")
cat("  cmd /c tools\\build_ia_paper.cmd\n")
cat("  bash tools/build_ia_paper.sh\n")
