###############################################################################
##
##  _create_djm_tabs_figs.R
##
##  Creates a LaTeX document compiling all tables and figures from the paper.
##  This script assumes the user has already run:
##    - _run_paper_results.R (unconditional model outputs)
##    - _run_paper_conditional_results.R (conditional model outputs)
##
##  Output:
##    - output/paper/latex/djm_main.tex (main document)
##    - output/paper/latex/tables.tex (table inputs)
##    - output/paper/latex/figures.tex (figure inputs)
##    - output/paper/latex/app_tables.tex (appendix table inputs)
##    - output/paper/latex/bibliography_2025_11_12.bib (bibliography)
##
###############################################################################

###############################################################################
## 1. CONFIGURATION
###############################################################################

# Project root path
main_path <- getwd()

# Output paths
output_base   <- file.path(main_path, "output", "paper")
tables_dir    <- file.path(output_base, "tables")
figures_dir   <- file.path(output_base, "figures")
latex_dir     <- file.path(output_base, "latex")

# Create latex directory if it doesn't exist
if (!dir.exists(latex_dir)) {
  dir.create(latex_dir, recursive = TRUE)
  cat("Created directory:", latex_dir, "\n")
}

# Verbose output
verbose <- TRUE

###############################################################################
## 2. TABLE ORDERING CONFIGURATION
###############################################################################

# Define the order in which tables should appear
# Main body tables (numbered 1-6)
main_table_order <- c(
  "table_1_top5_factors.tex",
  "table_2_is_pricing.tex",
  "table_3_os_pricing.tex",
  "table_4_sr_by_factor_type.tex",
  "table_5_dr_vs_cf.tex",
  "table_6_panel_a_trading.tex",
  "table_6_panel_b_trading.tex"
)

# Appendix tables (if any exist, pattern: table_a* or table_ia*)
appendix_table_patterns <- c("^table_a", "^table_ia")

###############################################################################
## 3. SCAN FOR AVAILABLE FILES
###############################################################################

cat("\n")
cat("========================================\n")
cat("CREATING LATEX DOCUMENT\n")
cat("========================================\n\n")

# Scan tables directory
if (dir.exists(tables_dir)) {
  all_tables <- list.files(tables_dir, pattern = "\\.tex$", full.names = FALSE)
  cat("Found", length(all_tables), "table files in:", tables_dir, "\n")
} else {
  all_tables <- character(0)
  warning("Tables directory does not exist: ", tables_dir)
}

# Scan figures directory (exclude fig_ai_* figures)
if (dir.exists(figures_dir)) {
  all_figures <- list.files(figures_dir, pattern = "\\.pdf$", full.names = FALSE)
  # Exclude fig_ai_* figures
  all_figures <- all_figures[!grepl("^fig_ai_", all_figures)]
  cat("Found", length(all_figures), "figure files in:", figures_dir, "\n")
} else {
  all_figures <- character(0)
  warning("Figures directory does not exist: ", figures_dir)
}

cat("\n")

###############################################################################
## 4. CREATE tables.tex
###############################################################################

cat("Creating tables.tex...\n")

# Separate main tables from appendix tables
main_tables <- intersect(main_table_order, all_tables)
appendix_tables <- character(0)
for (pattern in appendix_table_patterns) {
  appendix_tables <- c(appendix_tables, all_tables[grepl(pattern, all_tables, ignore.case = TRUE)])
}

# Any tables not in main_table_order and not matching appendix patterns go at the end
other_tables <- setdiff(all_tables, c(main_tables, appendix_tables))

# Build tables.tex content
tables_tex <- character()
tables_tex <- c(tables_tex, "% tables.tex - Auto-generated by _create_djm_tabs_figs.R")
tables_tex <- c(tables_tex, "% Contains all main body tables")
tables_tex <- c(tables_tex, "")

if (length(main_tables) > 0) {
  tables_tex <- c(tables_tex, "% Main Body Tables")
  tables_tex <- c(tables_tex, "% ================")
  for (tbl in main_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

if (length(other_tables) > 0) {
  tables_tex <- c(tables_tex, "% Additional Tables")
  tables_tex <- c(tables_tex, "% =================")
  for (tbl in other_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Write tables.tex
tables_tex_file <- file.path(latex_dir, "tables.tex")
writeLines(tables_tex, tables_tex_file)
cat("  Written:", tables_tex_file, "\n")
cat("  Included", length(main_tables) + length(other_tables), "tables\n")

###############################################################################
## 5. CREATE figures.tex
###############################################################################

cat("\nCreating figures.tex...\n")

# Read the figures template
figures_template_file <- file.path(main_path, "figures.txt")

if (file.exists(figures_template_file)) {
  figures_content <- readLines(figures_template_file)

  # Replace "Figures/" with "../figures/" for correct relative paths
  figures_content <- gsub("Figures/", "../figures/", figures_content)

  # Write figures.tex
  figures_tex_file <- file.path(latex_dir, "figures.tex")
  writeLines(figures_content, figures_tex_file)
  cat("  Written:", figures_tex_file, "\n")
  cat("  (Based on figures.txt template with adjusted paths)\n")
} else {
  # If no template, create a basic figures.tex from available figures
  cat("  No figures.txt template found. Creating from available figures...\n")

  figures_tex <- character()
  figures_tex <- c(figures_tex, "% figures.tex - Auto-generated by _create_djm_tabs_figs.R")
  figures_tex <- c(figures_tex, "% Contains all figures")
  figures_tex <- c(figures_tex, "")

  # Sort figures by name (they should be numbered fig1, fig2, etc.)
  all_figures <- sort(all_figures)

  for (fig in all_figures) {
    fig_name <- tools::file_path_sans_ext(fig)
    figures_tex <- c(figures_tex, "\\begin{figure}[tbh!]")
    figures_tex <- c(figures_tex, "\\begin{center}")
    figures_tex <- c(figures_tex, paste0("\\includegraphics[scale=.45]{../figures/", fig, "}"))
    figures_tex <- c(figures_tex, "\\end{center}")
    figures_tex <- c(figures_tex, paste0("\\caption{", gsub("_", " ", fig_name), "}"))
    figures_tex <- c(figures_tex, paste0("\\label{fig:", fig_name, "}"))
    figures_tex <- c(figures_tex, "\\end{figure}")
    figures_tex <- c(figures_tex, "\\clearpage")
    figures_tex <- c(figures_tex, "")
  }

  figures_tex_file <- file.path(latex_dir, "figures.tex")
  writeLines(figures_tex, figures_tex_file)
  cat("  Written:", figures_tex_file, "\n")
  cat("  Included", length(all_figures), "figures\n")
}

###############################################################################
## 6. CREATE app_tables.tex
###############################################################################

cat("\nCreating app_tables.tex...\n")

app_tables_tex <- character()
app_tables_tex <- c(app_tables_tex, "% app_tables.tex - Auto-generated by _create_djm_tabs_figs.R")
app_tables_tex <- c(app_tables_tex, "% Contains appendix tables")
app_tables_tex <- c(app_tables_tex, "")

if (length(appendix_tables) > 0) {
  app_tables_tex <- c(app_tables_tex, "% Appendix Tables")
  app_tables_tex <- c(app_tables_tex, "% ===============")
  for (tbl in appendix_tables) {
    app_tables_tex <- c(app_tables_tex, paste0("\\input{../tables/", tbl, "}"))
    app_tables_tex <- c(app_tables_tex, "\\clearpage")
    app_tables_tex <- c(app_tables_tex, "")
  }
} else {
  app_tables_tex <- c(app_tables_tex, "% No appendix tables found")
  app_tables_tex <- c(app_tables_tex, "% Add appendix tables to output/paper/tables/ with names starting with")
  app_tables_tex <- c(app_tables_tex, "% 'table_a' or 'table_ia' to have them included here automatically.")
  app_tables_tex <- c(app_tables_tex, "")
}

# Write app_tables.tex
app_tables_tex_file <- file.path(latex_dir, "app_tables.tex")
writeLines(app_tables_tex, app_tables_tex_file)
cat("  Written:", app_tables_tex_file, "\n")
cat("  Included", length(appendix_tables), "appendix tables\n")

###############################################################################
## 7. CREATE bibliography_2025_11_12.bib
###############################################################################

cat("\nCreating bibliography_2025_11_12.bib...\n")

bib_content <- '% bibliography_2025_11_12.bib - Auto-generated by _create_djm_tabs_figs.R
% Contains references used in the paper

@article{FamaFrench_1993,
	author = {Eugene F. Fama and Kenneth R. French},
	journal = {Journal of Financial Economics},
	pages = {3--56},
	title = {Common Risk Factors in the Returns on Stocks and Bonds},
	volume = {33},
	year = {1993}}

@article{HeKellyManela_2017,
	author = {He, Zhiguo and Kelly, Bryan and Manela, Asaf},
	journal = {Journal of Financial Economics},
	number = {1},
	pages = {1--35},
	publisher = {Elsevier},
	title = {Intermediary Asset Pricing: New Evidence From Many Asset Classes},
	volume = {126},
	year = {2017}}

@article{KozakNagelSantosh_2020,
	author = {Kozak, Serhiy and Nagel, Stefan and Santosh, Shrihari},
	issue = 2,
	journal = {Journal of Financial Economics},
	pages = {271--292},
	title = {Shrinking the Cross-Section},
	volume = 135,
	year = {2020}}

@article{LettauPelger_2020,
	author = {Lettau, Martin and Pelger, Markus},
	journal = {Journal of Econometrics},
	number = {1},
	pages = {1--31},
	title = {Estimating Latent Asset-Pricing Factors},
	volume = {218},
	year = {2020}}

@article{Vuolteenaho_2002,
	author = {Vuolteenaho, Tuomo},
	journal = {The Journal of Finance},
	number = {1},
	pages = {233--264},
	publisher = {Wiley Online Library},
	title = {What Drives Firm-Level Stock Returns?},
	volume = {57},
	year = {2002}}

@article{NeweyWest_1987,
	author = {Newey, Whitney K and West, Kenneth D.},
	journal = {Econometrica},
	number = {3},
	pages = {703--708},
	title = {A Simple, Positive Semi-definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix},
	volume = {55},
	year = {1987}}
'

bib_file <- file.path(latex_dir, "bibliography_2025_11_12.bib")
writeLines(bib_content, bib_file)
cat("  Written:", bib_file, "\n")

###############################################################################
## 8. CREATE djm_main.tex
###############################################################################

cat("\nCreating djm_main.tex...\n")

# Read the base document template
base_doc_file <- file.path(main_path, "base_document.txt")

if (!file.exists(base_doc_file)) {
  stop("Base document template not found: ", base_doc_file)
}

main_doc <- readLines(base_doc_file)

# Add \clearpage before \input{app_tables.tex}
# Find the line with \input{app_tables.tex} and insert \clearpage before it
app_tables_line <- grep("\\\\input\\{app_tables\\.tex\\}", main_doc)
if (length(app_tables_line) > 0) {
  # Insert \clearpage before app_tables.tex
  main_doc <- c(
    main_doc[1:(app_tables_line[1] - 1)],
    "\\clearpage",
    main_doc[app_tables_line[1]:length(main_doc)]
  )
  cat("  Added \\clearpage before \\input{app_tables.tex}\n")
}

# Write djm_main.tex
main_tex_file <- file.path(latex_dir, "djm_main.tex")
writeLines(main_doc, main_tex_file)
cat("  Written:", main_tex_file, "\n")

###############################################################################
## 9. SUMMARY
###############################################################################

cat("\n")
cat("========================================\n")
cat("LATEX DOCUMENT CREATION COMPLETE\n")
cat("========================================\n\n")

cat("Output directory:", latex_dir, "\n\n")

cat("Files created:\n")
cat("  1. djm_main.tex              - Main LaTeX document\n")
cat("  2. tables.tex                - Table inputs (", length(main_tables) + length(other_tables), " tables)\n", sep = "")
cat("  3. figures.tex               - Figure inputs\n")
cat("  4. app_tables.tex            - Appendix table inputs (", length(appendix_tables), " tables)\n", sep = "")
cat("
  5. bibliography_2025_11_12.bib - Bibliography file\n")

cat("\n")
cat("To compile the document:\n")
cat("  1. cd", latex_dir, "\n")
cat("  2. pdflatex djm_main.tex\n")
cat("  3. bibtex bu1  (for bibliography)\n")
cat("  4. pdflatex djm_main.tex\n")
cat("  5. pdflatex djm_main.tex\n")

cat("\n")
cat("Note: The bibliography file has been auto-generated.\n")
cat("      Ensure all required .sty files are available.\n")
cat("\n")
