###############################################################################
##
##  _create_djm_tabs_figs.R
##
##  Creates a LaTeX document compiling all tables and figures from the paper.
##  This script assumes the user has already run:
##    - _run_paper_results.R (unconditional model outputs)
##    - _run_paper_conditional_results.R (conditional model outputs)
##
##  Output:
##    - output/paper/latex/djfm_main.tex (main document)
##    - output/paper/latex/tables.tex (table inputs)
##    - output/paper/latex/figures.tex (figure inputs)
##    - output/paper/latex/app_tables.tex (appendix table inputs)
##
###############################################################################

###############################################################################
## 1. CONFIGURATION
###############################################################################

# Project root path
main_path <- getwd()

# Output paths
output_base   <- file.path(main_path, "output", "paper")
tables_dir    <- file.path(output_base, "tables")
figures_dir   <- file.path(output_base, "figures")
latex_dir     <- file.path(output_base, "latex")

# Create latex directory if it doesn't exist
if (!dir.exists(latex_dir)) {
  dir.create(latex_dir, recursive = TRUE)
  cat("Created directory:", latex_dir, "\n")
}

# Verbose output
verbose <- TRUE

###############################################################################
## 2. TABLE ORDERING CONFIGURATION
###############################################################################

# Define the order in which tables should appear
# Main body tables (numbered 1-6)
main_table_order <- c(

  "table_1_top5_factors.tex",
  "table_2_is_pricing.tex",
  "table_3_os_pricing.tex",
  "table_4_sr_by_factor_type.tex",
  "table_5_dr_vs_cf.tex",
  "table_6_panel_a_trading.tex",
  "table_6_panel_b_trading.tex"
)

# Appendix tables (if any exist, pattern: table_a* or table_ia*)
appendix_table_patterns <- c("^table_a", "^table_ia")

###############################################################################
## 3. SCAN FOR AVAILABLE FILES
###############################################################################

cat("\n")
cat("========================================\n")
cat("CREATING LATEX DOCUMENT\n")
cat("========================================\n\n")

# Scan tables directory
if (dir.exists(tables_dir)) {
  all_tables <- list.files(tables_dir, pattern = "\\.tex$", full.names = FALSE)
  cat("Found", length(all_tables), "table files in:", tables_dir, "\n")
} else {
  all_tables <- character(0)
  warning("Tables directory does not exist: ", tables_dir)
}

# Scan figures directory (exclude fig_ai_* figures)
if (dir.exists(figures_dir)) {
  all_figures <- list.files(figures_dir, pattern = "\\.pdf$", full.names = FALSE)
  # Exclude fig_ai_* figures
  all_figures <- all_figures[!grepl("^fig_ai_", all_figures)]
  cat("Found", length(all_figures), "figure files in:", figures_dir, "\n")
} else {
  all_figures <- character(0)
  warning("Figures directory does not exist: ", figures_dir)
}

cat("\n")

###############################################################################
## 4. CREATE tables.tex
###############################################################################

cat("Creating tables.tex...\n")

# Separate main tables from appendix tables
main_tables <- intersect(main_table_order, all_tables)
appendix_tables <- character(0)
for (pattern in appendix_table_patterns) {
  appendix_tables <- c(appendix_tables, all_tables[grepl(pattern, all_tables, ignore.case = TRUE)])
}

# Any tables not in main_table_order and not matching appendix patterns go at the end
other_tables <- setdiff(all_tables, c(main_tables, appendix_tables))

# Build tables.tex content
tables_tex <- character()
tables_tex <- c(tables_tex, "% tables.tex - Auto-generated by _create_djm_tabs_figs.R")
tables_tex <- c(tables_tex, "% Contains all main body tables")
tables_tex <- c(tables_tex, "")

if (length(main_tables) > 0) {
  tables_tex <- c(tables_tex, "% Main Body Tables")
  tables_tex <- c(tables_tex, "% ================")
  for (tbl in main_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

if (length(other_tables) > 0) {
  tables_tex <- c(tables_tex, "% Additional Tables")
  tables_tex <- c(tables_tex, "% =================")
  for (tbl in other_tables) {
    tables_tex <- c(tables_tex, paste0("\\input{../tables/", tbl, "}"))
    tables_tex <- c(tables_tex, "\\clearpage")
    tables_tex <- c(tables_tex, "")
  }
}

# Write tables.tex
tables_tex_file <- file.path(latex_dir, "tables.tex")
writeLines(tables_tex, tables_tex_file)
cat("  Written:", tables_tex_file, "\n")
cat("  Included", length(main_tables) + length(other_tables), "tables\n")

###############################################################################
## 5. CREATE figures.tex
###############################################################################

cat("\nCreating figures.tex...\n")

# Read the figures template
figures_template_file <- file.path(main_path, "figures.txt")

if (file.exists(figures_template_file)) {
  figures_content <- readLines(figures_template_file)

  # Replace "Figures/" with "../figures/" for correct relative paths
  figures_content <- gsub("Figures/", "../figures/", figures_content)

  # Write figures.tex
  figures_tex_file <- file.path(latex_dir, "figures.tex")
  writeLines(figures_content, figures_tex_file)
  cat("  Written:", figures_tex_file, "\n")
  cat("  (Based on figures.txt template with adjusted paths)\n")
} else {
  # If no template, create a basic figures.tex from available figures
  cat("  No figures.txt template found. Creating from available figures...\n")

  figures_tex <- character()
  figures_tex <- c(figures_tex, "% figures.tex - Auto-generated by _create_djm_tabs_figs.R")
  figures_tex <- c(figures_tex, "% Contains all figures")
  figures_tex <- c(figures_tex, "")

  # Sort figures by name (they should be numbered fig1, fig2, etc.)
  all_figures <- sort(all_figures)

  for (fig in all_figures) {
    fig_name <- tools::file_path_sans_ext(fig)
    figures_tex <- c(figures_tex, "\\begin{figure}[tbh!]")
    figures_tex <- c(figures_tex, "\\begin{center}")
    figures_tex <- c(figures_tex, paste0("\\includegraphics[scale=.45]{../figures/", fig, "}"))
    figures_tex <- c(figures_tex, "\\end{center}")
    figures_tex <- c(figures_tex, paste0("\\caption{", gsub("_", " ", fig_name), "}"))
    figures_tex <- c(figures_tex, paste0("\\label{fig:", fig_name, "}"))
    figures_tex <- c(figures_tex, "\\end{figure}")
    figures_tex <- c(figures_tex, "\\clearpage")
    figures_tex <- c(figures_tex, "")
  }

  figures_tex_file <- file.path(latex_dir, "figures.tex")
  writeLines(figures_tex, figures_tex_file)
  cat("  Written:", figures_tex_file, "\n")
  cat("  Included", length(all_figures), "figures\n")
}

###############################################################################
## 6. CREATE app_tables.tex
###############################################################################

cat("\nCreating app_tables.tex...\n")

app_tables_tex <- character()
app_tables_tex <- c(app_tables_tex, "% app_tables.tex - Auto-generated by _create_djm_tabs_figs.R")
app_tables_tex <- c(app_tables_tex, "% Contains appendix tables")
app_tables_tex <- c(app_tables_tex, "")

if (length(appendix_tables) > 0) {
  app_tables_tex <- c(app_tables_tex, "% Appendix Tables")
  app_tables_tex <- c(app_tables_tex, "% ===============")
  for (tbl in appendix_tables) {
    app_tables_tex <- c(app_tables_tex, paste0("\\input{../tables/", tbl, "}"))
    app_tables_tex <- c(app_tables_tex, "\\clearpage")
    app_tables_tex <- c(app_tables_tex, "")
  }
} else {
  app_tables_tex <- c(app_tables_tex, "% No appendix tables found")
  app_tables_tex <- c(app_tables_tex, "% Add appendix tables to output/paper/tables/ with names starting with")
  app_tables_tex <- c(app_tables_tex, "% 'table_a' or 'table_ia' to have them included here automatically.")
  app_tables_tex <- c(app_tables_tex, "")
}

# Write app_tables.tex
app_tables_tex_file <- file.path(latex_dir, "app_tables.tex")
writeLines(app_tables_tex, app_tables_tex_file)
cat("  Written:", app_tables_tex_file, "\n")
cat("  Included", length(appendix_tables), "appendix tables\n")

###############################################################################
## 7. CREATE djfm_main.tex
###############################################################################

cat("\nCreating djfm_main.tex...\n")

# Read the base document template
base_doc_file <- file.path(main_path, "base_document.txt")

if (!file.exists(base_doc_file)) {
  stop("Base document template not found: ", base_doc_file)
}

main_doc <- readLines(base_doc_file)

# The base document already has the correct structure with:
# \input{tables.tex}
# \input{figures.tex}
# \input{app_tables.tex}
# No modifications needed to the content, just copy it

# Write djfm_main.tex
main_tex_file <- file.path(latex_dir, "djfm_main.tex")
writeLines(main_doc, main_tex_file)
cat("  Written:", main_tex_file, "\n")

###############################################################################
## 8. SUMMARY
###############################################################################

cat("\n")
cat("========================================\n")
cat("LATEX DOCUMENT CREATION COMPLETE\n")
cat("========================================\n\n")

cat("Output directory:", latex_dir, "\n\n")

cat("Files created:\n")
cat("  1. djfm_main.tex   - Main LaTeX document\n")
cat("  2. tables.tex      - Table inputs (", length(main_tables) + length(other_tables), " tables)\n", sep = "")
cat("  3. figures.tex     - Figure inputs\n")
cat("  4. app_tables.tex  - Appendix table inputs (", length(appendix_tables), " tables)\n", sep = "")

cat("\n")
cat("To compile the document:\n")
cat("  1. Copy bibliography file to:", latex_dir, "\n")
cat("  2. cd", latex_dir, "\n")
cat("  3. pdflatex djfm_main.tex\n")
cat("  4. bibtex bu1  (for bibliography)\n")
cat("  5. pdflatex djfm_main.tex\n")
cat("  6. pdflatex djfm_main.tex\n")

cat("\n")
cat("Note: Ensure all required .sty files and the bibliography file\n")
cat("      (bibliography_2025_11_12.bib) are in the latex directory.\n")
cat("\n")
